<DocumentHistory geneiousVersion="2019.2.1">
  <entryFields>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.date fieldName="Created">1484889653650</com.biomatters.date>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.user fieldName="User">Matt.Kearse</com.biomatters.user>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.geneiousVersion fieldName="Geneious Version">10.1.0</com.biomatters.geneiousVersion>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <description fieldName="Imported from">C:\temp\yghJ Ion Torrent reads.fastq</description>
    </DocumentHistoryEntryField>
  </entryFields>
  <entryFields>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.date fieldName="Saved">1484889661138</com.biomatters.date>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.user fieldName="User">Matt.Kearse</com.biomatters.user>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.geneiousVersion fieldName="Geneious Version">10.1.0</com.biomatters.geneiousVersion>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.autogeneratedEntry fieldName="" />
    </DocumentHistoryEntryField>
  </entryFields>
  <entryFields>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.date fieldName="Saved">1484889677985</com.biomatters.date>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.user fieldName="User">Matt.Kearse</com.biomatters.user>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.geneiousVersion fieldName="Geneious Version">10.1.0</com.biomatters.geneiousVersion>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.autogeneratedEntry fieldName="" />
    </DocumentHistoryEntryField>
  </entryFields>
  <entryFields>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.date fieldName="Saved">1484889686113</com.biomatters.date>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.user fieldName="User">Matt.Kearse</com.biomatters.user>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.geneiousVersion fieldName="Geneious Version">10.1.0</com.biomatters.geneiousVersion>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.autogeneratedEntry fieldName="" />
    </DocumentHistoryEntryField>
  </entryFields>
  <entryFields>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.date fieldName="Saved">1484889686145</com.biomatters.date>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.user fieldName="User">Matt.Kearse</com.biomatters.user>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.geneiousVersion fieldName="Geneious Version">10.1.0</com.biomatters.geneiousVersion>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.autogeneratedEntry fieldName="" />
    </DocumentHistoryEntryField>
  </entryFields>
  <entryFields>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.date fieldName="Saved">1484889690431</com.biomatters.date>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.user fieldName="User">Matt.Kearse</com.biomatters.user>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.geneiousVersion fieldName="Geneious Version">10.1.0</com.biomatters.geneiousVersion>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.autogeneratedEntry fieldName="" />
    </DocumentHistoryEntryField>
  </entryFields>
  <entryFields>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.date fieldName="Saved">1484889690462</com.biomatters.date>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.user fieldName="User">Matt.Kearse</com.biomatters.user>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.geneiousVersion fieldName="Geneious Version">10.1.0</com.biomatters.geneiousVersion>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.autogeneratedEntry fieldName="" />
    </DocumentHistoryEntryField>
  </entryFields>
  <entryFields>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.date fieldName="Saved">1484889699006</com.biomatters.date>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.user fieldName="User">Matt.Kearse</com.biomatters.user>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.geneiousVersion fieldName="Geneious Version">10.1.0</com.biomatters.geneiousVersion>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.autogeneratedEntry fieldName="" />
    </DocumentHistoryEntryField>
  </entryFields>
  <entryFields>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.date fieldName="Modified">1484889699017</com.biomatters.date>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.user fieldName="User">Matt.Kearse</com.biomatters.user>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.geneiousVersion fieldName="Geneious Version">10.1.0</com.biomatters.geneiousVersion>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.optionsValues fieldName="Options">&lt;options&gt;
  &lt;option name="dataType"&gt;Ion Torrent&lt;/option&gt;
&lt;/options&gt;</com.biomatters.optionsValues>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField name="Input Document" type="com.biomatters.geneious.publicapi.documents.DocumentHistoryReferencedDocumentsEntryField">
      <entry>
        <revision>8</revision>
        <urn class="urn" weakReference="true">urn:local:.:3q-ao37c7v</urn>
      </entry>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.operationUniqueId fieldName="">com.biomatters.plugins.groupSequences.SetDataTypeOperation</com.biomatters.operationUniqueId>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <description fieldName="Operation:">Set Read Technology</description>
    </DocumentHistoryEntryField>
  </entryFields>
  <entryFields>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.date fieldName="Saved">1484889699033</com.biomatters.date>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.user fieldName="User">Matt.Kearse</com.biomatters.user>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.geneiousVersion fieldName="Geneious Version">10.1.0</com.biomatters.geneiousVersion>
    </DocumentHistoryEntryField>
    <DocumentHistoryEntryField class="com.biomatters.geneious.publicapi.documents.DocumentHistoryEntryFieldImplementation">
      <com.biomatters.autogeneratedEntry fieldName="" />
    </DocumentHistoryEntryField>
  </entryFields>
</DocumentHistory>